# Environment variables to be defined in the build configuration:
# AUTH0_TEST_CLIENT_ID = Client id to use in test
# AUTH0_TEST_DOMAIN = Domain to use in test
# AUTH0_TEST_API_IDENTIFIER = API Audience to use in test

# Common logic
defaults: &defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Creating environment variables
          command: |
            echo "AUTH0_CLIENT_ID=$AUTH0_TEST_CLIENT_ID" >> $AUTH0_CFG
            echo "AUTH0_DOMAIN=$AUTH0_TEST_DOMAIN">> $AUTH0_CFG
            echo "AUTH0_CLIENT_SECRET=$AUTH0_TEST_CLIENT_SECRET">> $AUTH0_CFG
            echo "AUTH0_CALLBACK_URL=http://localhost:3000/callback">> $AUTH0_CFG
            echo "AUTH0_AUDIENCE=">> $AUTH0_CFG
      - run:
          name: Execute dockerized example
          command: |
            docker build -t $CIRCLE_JOB ./$SAMPLE_PATH
            docker run -d -p 3000:3000 --name $CIRCLE_SHA1 -e AUTH0_DOMAIN=$AUTH0_TEST_DOMAIN -e AUTH0_AUDIENCE=$AUTH0_TEST_API_IDENTIFIER $CIRCLE_JOB
      - run:
          name: Wait for app to be available
          command: |
                sleep 10
                docker run --network host --rm appropriate/curl -v localhost:3000 
     #      docker run --network host --rm appropriate/curl --retry 8 --retry-connrefused -v localhost:3000
      - run: 
          name: Run tests
          command: |
            docker create --network host --name tester codeception/codeceptjs codeceptjs run-multiple --verbose --all --steps
            docker cp $(pwd)/lock_login_test.js tester:/tests/lock_login_test.js
            docker cp $(pwd)/codecept.conf.js tester:/tests/codecept.conf.js
            docker start -i tester
          working_directory: scripts
      #- run:
      #    name: Copy app container logs
      #    command: |
      #      mkdir -p /tmp/out
      #      docker logs $CIRCLE_SHA1 > /tmp/out/app_logs.log
      #      docker cp tester:/tests/out /tmp/
      #    when: on_fail
      #- store_artifacts:
      #    path: /tmp/out

# Jobs and Workflows
version: 2
jobs: 
  checkout:
    machine: true
    steps:
      - checkout
      - run: git clone https://github.com/rafanog/spa-script scripts
      - persist_to_workspace:
          root: ~/ 
          paths:
            - project
            - scripts
  01-login:
    machine: true
    environment:
      - AUTH0_CFG: 01-Login/.env
      - SAMPLE_PATH: 01-Login
    <<: *defaults

workflows:
  version: 2
  quickstarts_login:
    jobs:
      - checkout:
          context: Quickstart SPA Test
      - 01-login:
          context: Quickstart SPA Test
          requires:
            - checkout
